export type Stage = "idea" | "research" | "building" | "launched"

export interface Project {
  id: string
  title: string
  description: string
  stage: Stage
  score: number
  tier: "S" | "A" | "B"
  market: number
  pain: number
  mono: number
  speed: number
  competition: number
  audience: string
  price: string
  tags: string[]
  competitors: string[]
  createdAt: string
  whyNow: string
  risks: string[]
  nextSteps: string[]
}

export const stageLabel: Record<Stage, string> = {
  idea: "Идея",
  research: "Исследование",
  building: "Разработка",
  launched: "Запущен",
}

export const stageColor: Record<Stage, string> = {
  idea: "#F59E0B",
  research: "#3B82F6",
  building: "#6366F1",
  launched: "#22C55E",
}

export const initialProjects: Project[] = [
  // ─── TIER S ───────────────────────────────────────────────────────────────
  {
    id: "001-contract-agent",
    title: "ContractAgent",
    description: "AI агент который автономно управляет корпоративными контрактами для SMB (10-200 чел): извлечение из email, трекинг renewals, алерты, action plan.",
    stage: "building",
    score: 7.9, tier: "S",
    market: 7, pain: 9, mono: 8, speed: 7, competition: 8,
    audience: "SMB компании 10-200 сотрудников",
    price: "$199/мес",
    tags: ["AI Agent", "Legal", "SaaS", "SMB"],
    competitors: ["ContractSafe ($99-299, нет AI)", "Ironclad ($65+/user, Enterprise)", "PactAlert (маленький)"],
    createdAt: "2026-03-01",
    whyNow: "56% компаний пропускают renewals, 9% выручки теряется из-за плохого контракт-менеджмента. AI сделал extraction из неструктурированных документов точным. SMB gap реален — конкуренты дорогие или слабые.",
    risks: ["Enterprise конкуренты могут снизить цены", "Юридическая ответственность за пропущенные клаузулы", "Длинный цикл продаж в B2B", "Интеграция с разными email провайдерами"],
    nextSteps: ["Интервью с 10 офис-менеджерами SMB", "MVP: extraction из Gmail → Google Sheet", "Waitlist лендинг", "5 платных пилотов по $199/мес", "Интеграция с DocuSign"],
  },
  {
    id: "002-content-agent",
    title: "ContentAgent «Record Once»",
    description: "AI агент превращает podcast/видео во все форматы и публикует везде автоматически. Обучается голосу создателя — через 3 месяца невозможно скопировать.",
    stage: "idea",
    score: 7.4, tier: "S",
    market: 9, pain: 8, mono: 7, speed: 5, competition: 7,
    audience: "Podcast creators, YouTubers, маркетологи",
    price: "$79-149/мес",
    tags: ["AI Agent", "Content", "Creator", "Automation"],
    competitors: ["Castmagic ($39-249, только audio)", "Opus Clip ($19-49, только клипы)", "Repurpose.io ($25-99, нет AI)"],
    createdAt: "2026-03-02",
    whyNow: "Рынок creator tools $1B → $3.5B к 2027. Никто не делает full pipeline (запись → все форматы → публикация). После 3 месяцев агент знает голос creator — мощный lock-in.",
    risks: ["Сложный build (10-12 недель)", "API изменения у соцсетей", "Качество транскрипции для не-английского"],
    nextSteps: ["Строить вторым после ContractAgent достигает $5k MRR", "Выбрать одну платформу вывода (LinkedIn posts)", "Beta с 20 подкастерами"],
  },

  // ─── TIER A ───────────────────────────────────────────────────────────────
  {
    id: "003-outreach-agent",
    title: "OutreachAgent",
    description: "AI агент для B2B продаж. Говоришь «найди 100 ICP и начни разговор» → агент исследует компании, пишет персонализированные письма, ведёт диалог.",
    stage: "idea",
    score: 7.6, tier: "A",
    market: 9, pain: 8, mono: 9, speed: 6, competition: 6,
    audience: "SDR, агентства, B2B founders",
    price: "$50 за квалифицированный лид",
    tags: ["AI Agent", "Sales", "B2B", "Outreach"],
    competitors: ["Apollo.io", "Lemlist", "Hunter.io", "Smartwriter"],
    createdAt: "2026-03-03",
    whyNow: "Outcome-based pricing ($50/лид) = клиент платит только за результат. Существующие инструменты не agentic — ты сам всё настраиваешь. AI agent реально ведёт диалог.",
    risks: ["Высокая конкуренция", "Email deliverability ограничения", "Spam фильтры становятся умнее", "Юридические ограничения GDPR"],
    nextSteps: ["Тест с собственными cold outreach кампаниями", "Интеграция с Apollo для данных", "MVP: research + draft + send через Gmail API", "10 beta клиентов на outcome-based pricing"],
  },
  {
    id: "004-compliance-agent",
    title: "ComplianceAgent",
    description: "Следит за изменениями в законодательстве → пишет plain-English summary → составляет action plan. Для fintech, health, legal SMB.",
    stage: "idea",
    score: 7.6, tier: "A",
    market: 8, pain: 8, mono: 8, speed: 6, competition: 8,
    audience: "SMB в регулируемых индустриях (fintech, health, legal)",
    price: "$299/мес",
    tags: ["AI Agent", "Legal", "Compliance", "B2B"],
    competitors: ["Thomson Reuters (enterprise)", "LexisNexis (enterprise)", "Comply.ai (ранний)"],
    createdAt: "2026-03-04",
    whyNow: "Compliance miss = штрафы = очень дорого. В SMB сегменте почти нет решений — все для enterprise. Регуляции становятся сложнее каждый год.",
    risks: ["Нужна юридическая экспертиза для контент-ревью", "Ответственность за пропущенные изменения", "Медленный цикл продаж"],
    nextSteps: ["Выбрать одну вертикаль (fintech)", "Найти партнёра с юридической экспертизой", "MVP: мониторинг одного регулятора (SEC/FCA)", "5 пилотных клиентов"],
  },
  {
    id: "005-support-agent",
    title: "SupportAgent",
    description: "AI агент который реально решает тикеты (рефанды, смена настроек, escalation) — не FAQ бот. Обучен на данных клиента.",
    stage: "idea",
    score: 7.2, tier: "A",
    market: 9, pain: 7, mono: 8, speed: 6, competition: 6,
    audience: "E-commerce, SaaS компании с большим объёмом тикетов",
    price: "$2-5 за закрытый тикет",
    tags: ["AI Agent", "Support", "SaaS", "E-commerce"],
    competitors: ["Intercom (generic AI)", "Zendesk AI (generic)", "Freshdesk (generic)"],
    createdAt: "2026-03-05",
    whyNow: "Существующие AI в support — generic FAQ боты. Агент обученный на данных конкретного клиента может реально закрывать тикеты: рефанды, апгрейды, изменения настроек.",
    risks: ["Интеграция с существующими helpdesk системами", "Ответственность за неправильные рефанды", "Сложность обучения на данных каждого клиента"],
    nextSteps: ["Выбрать нишу (Shopify магазины)", "Интеграция с Gorgias/Zendesk API", "MVP с 3 типами тикетов (рефанд, статус заказа, смена адреса)", "Тест на 1 магазине"],
  },
  {
    id: "006-listing-agent",
    title: "ListingAgent (Amazon)",
    description: "AI агент постоянно мониторит Amazon листинги vs конкуренты и оптимизирует. Не генератор — постоянный competitive intelligence агент.",
    stage: "research",
    score: 7.0, tier: "A",
    market: 9, pain: 7, mono: 7, speed: 7, competition: 5,
    audience: "Amazon FBA sellers (9.7M активных)",
    price: "$79-149/мес",
    tags: ["AI Agent", "Amazon", "E-commerce", "Monitor"],
    competitors: ["Flowin.ai", "CopyMonkey", "Perci", "ZonGuru", "Epinium", "Helium10"],
    createdAt: "2026-03-06",
    whyNow: "Существующие инструменты — one-time generators. Нет агента который постоянно мониторит конкурентов и еженедельно присылает briefing с рекомендациями.",
    risks: ["Рынок более конкурентный чем казалось", "Конкуренты могут добавить monitoring за 2 месяца", "Amazon API ограничения"],
    nextSteps: ["Positioning: «постоянный competitive intelligence», не listing generator", "Interview 20 FBA sellers про боль monitoring", "MVP: еженедельный email briefing"],
  },
  {
    id: "011-freelance-payment",
    title: "FreelancePaymentAgent",
    description: "AI агент следит за неоплаченными инвойсами → сам отправляет follow-up письма → меняет тон (friendly → firm → formal) → эскалирует если игнорируют.",
    stage: "idea",
    score: 7.6, tier: "A",
    market: 8, pain: 9, mono: 8, speed: 7, competition: 6,
    audience: "Фрилансеры, консультанты, малые агентства",
    price: "$29-49/мес",
    tags: ["AI Agent", "Finance", "Freelance", "Automation"],
    competitors: ["HoneyBook (напоминания, не agentic)", "Bonsai (напоминания, не agentic)", "FreshBooks"],
    createdAt: "2026-03-07",
    whyNow: "Reddit опрос 3200+ фрилансеров: #1 проблема — поздние/неоплаченные счета. Тратят 2+ часа в неделю на chase за оплатой. Потери $10k в год. Нет агента который реально ведёт диалог с клиентом.",
    risks: ["Юридическая ответственность за тон письма", "Работа с разными валютами и юрисдикциями", "Интеграция с инвойс системами"],
    nextSteps: ["Интервью с 20 фрилансерами на Reddit r/freelance", "MVP: мониторинг Gmail + draft follow-up", "Тест с 5 beta фрилансерами", "Интеграция с FreshBooks API"],
  },
  {
    id: "012-therapist-agent",
    title: "TherapistAgent / PracticeAgent",
    description: "AI агент для частных психологов: автоматические заметки после сессии, scheduling, billing — всё в одном. Для solo practice.",
    stage: "idea",
    score: 7.1, tier: "A",
    market: 7, pain: 8, mono: 8, speed: 5, competition: 7,
    audience: "Частные психологи и терапевты (solo practice)",
    price: "$59-99/мес",
    tags: ["AI", "Healthcare", "SaaS", "Automation"],
    competitors: ["SimplePractice ($30-80/мес, не AI-native)", "TherapyNotes ($49+/мес, сложный)", "TheraNest"],
    createdAt: "2026-03-08",
    whyNow: "Тераписты тратят 30-60 мин после каждой сессии на ручные notes + billing. Существующие инструменты дорогие и сложные для solo practice. AI note generation стал точным.",
    risks: ["HIPAA compliance = юридическая сложность", "BAA нужна с каждым vendor", "Доверие к AI в медицине", "Длинный цикл валидации"],
    nextSteps: ["Исследовать HIPAA требования детально", "Найти HIPAA-compliant infrastructure партнёра", "Интервью с 10 терапистами", "MVP: audio → SOAP notes (без billing)"],
  },
  {
    id: "013-landlord-agent",
    title: "LandlordAgent",
    description: "AI агент для малых арендодателей (2-15 объектов): сбор аренды, напоминания, заявки на ремонт, скрининг арендаторов, хранение договоров.",
    stage: "idea",
    score: 7.1, tier: "A",
    market: 7, pain: 8, mono: 7, speed: 6, competition: 7,
    audience: "Малые арендодатели 2-15 объектов",
    price: "$49-99/мес",
    tags: ["AI Agent", "Real Estate", "SaaS", "Automation"],
    competitors: ["Buildium ($300+/мес, для 50+)", "TurboTenant (бесплатно, базовый)", "AppFolio ($300+/мес)"],
    createdAt: "2026-03-09",
    whyNow: "Reddit r/landlord — малые арендодатели используют Excel + личный телефон. Крупные платформы заточены под 50+ объектов. Огромный ценовой gap для 2-15 объектов.",
    risks: ["Юридические требования аренды разные по штатам", "Интеграция с банками для сбора оплат", "Ответственность за скрининг арендаторов"],
    nextSteps: ["Survey 30 landlords на Reddit r/landlord", "MVP: rent reminders + maintenance requests", "Интеграция со Stripe для rent collection", "Тест на 5 landlords"],
  },
  {
    id: "014-proposal-agent",
    title: "ProposalAgent",
    description: "AI агент создаёт персонализированный proposal за 5 минут: изучает клиента (сайт, LinkedIn), пишет proposal, учится на твоих победах и поражениях.",
    stage: "idea",
    score: 7.1, tier: "A",
    market: 8, pain: 8, mono: 7, speed: 7, competition: 5,
    audience: "Фрилансеры, агентства, консультанты",
    price: "$39-79/мес",
    tags: ["AI Agent", "Sales", "Freelance", "Documents"],
    competitors: ["Proposify ($49-590/мес, templates)", "PandaDoc (дорогой)", "Better Proposals"],
    createdAt: "2026-03-10",
    whyNow: "Фрилансеры пишут proposals 2-3 часа, высокий rejection rate. «Starting from scratch every single time» — самая частая жалоба. Существующие инструменты — шаблоны, не AI генерация.",
    risks: ["Зависимость от качества исходных данных клиента", "Сложность обучения на победах/поражениях", "LinkedIn API для research"],
    nextSteps: ["MVP: URL клиента → draft proposal за 5 минут", "Тест с 10 фрилансерами", "A/B тест proposal win rate", "Интеграция с Upwork/LinkedIn"],
  },
  {
    id: "015-meeting-notes-agent",
    title: "MeetingNotesAgent (нишевый)",
    description: "AI агент для вертикалей где обычные notes не подходят: юристы (legal memo), врачи (SOAP notes), sales coaches (coaching scorecard). Старт с юристами.",
    stage: "idea",
    score: 7.6, tier: "A",
    market: 8, pain: 8, mono: 9, speed: 6, competition: 7,
    audience: "Юристы, врачи, sales coaches (solo/small firm)",
    price: "$79-149/мес",
    tags: ["AI Agent", "Legal", "Productivity", "Vertical SaaS"],
    competitors: ["Otter.ai (generic)", "Fireflies (generic)", "Fathom (generic)"],
    createdAt: "2026-03-10",
    whyNow: "AI meeting assistants market $3.24B → $7.33B к 2035. Все generic — нишевые вертикали недообслуживаются. Юристы и врачи платят высокую WTP. Нет HIPAA у юристов — меньше риска.",
    risks: ["Выбор правильной вертикали критичен", "Врачи = HIPAA, сложнее", "Точность специализированной терминологии", "Интеграция с Zoom/Teams/Google Meet"],
    nextSteps: ["Выбрать ОДНУ вертикаль — юристы (нет HIPAA)", "Interview 15 solo/small firm юристов", "MVP: Zoom recording → legal memo format", "8-13 клиентов для $1k MRR"],
  },
  {
    id: "016-scope-creep-guard",
    title: "ScopeCreepGuard",
    description: "AI агент встроенный в email/Slack: детектирует когда клиент просит сверх контракта → генерирует change order → отправляет клиенту на подпись.",
    stage: "idea",
    score: 7.0, tier: "A",
    market: 7, pain: 8, mono: 6, speed: 6, competition: 8,
    audience: "Фрилансеры, агентства, консультанты",
    price: "$29-59/мес",
    tags: ["AI Agent", "Freelance", "Contracts", "Automation"],
    competitors: ["Нет прямых конкурентов", "ClickUp/Notion (косвенно, не автоматически)"],
    createdAt: "2026-03-11",
    whyNow: "Reddit r/freelance полон историй scope creep. Клиенты добавляют «just one more thing». Freelancer не замечает пока не сделал двойной объём. Нет автоматического решения.",
    risks: ["Сложно продать («я сам слежу»)", "Нужно показать $$ потерянные на scope creep", "Интеграция с email сложная", "False positives раздражают клиентов"],
    nextSteps: ["Валидация WTP: 30 фрилансеров на Reddit", "MVP: анализ email thread → предупреждение о scope creep", "Тест на себе 2 недели", "Лендинг с калькулятором «сколько ты теряешь на scope creep»"],
  },
  {
    id: "017-review-agent",
    title: "ReviewAgent",
    description: "AI агент для одиночного малого бизнеса (кафе, клиника, салон): мониторит Google/Yelp, сам отвечает на отзывы, просит довольных клиентов оставить отзыв.",
    stage: "idea",
    score: 7.2, tier: "A",
    market: 9, pain: 7, mono: 7, speed: 7, competition: 6,
    audience: "Одиночные кафе, клиники, салоны, рестораны",
    price: "$39-79/мес",
    tags: ["AI Agent", "Reviews", "Local Business", "Reputation"],
    competitors: ["Birdeye ($300+/мес, enterprise)", "Podium ($300+/мес, enterprise)", "ReviewTrackers"],
    createdAt: "2026-03-11",
    whyNow: "Решения для сетей ($300+/мес). Одиночный бизнес не может себе позволить. 1 звезда = -5-9% выручки. Огромный ценовой gap: enterprise vs ничего для малого бизнеса.",
    risks: ["Google API изменения", "Автоматические ответы могут звучать неестественно", "Сложность настройки голоса бизнеса"],
    nextSteps: ["Survey 20 владельцев ресторанов", "MVP: мониторинг Google Reviews + draft ответ", "Pricing тест $39/мес vs $79/мес", "Партнёрство с ресторанными ассоциациями"],
  },
  {
    id: "019-onboarding-agent",
    title: "OnboardingAgent (B2B SaaS)",
    description: "AI агент автоматически onboard'ит новых клиентов SaaS: обнаруживает где застрял → отправляет персонализированный email/Intercom → записывает на звонок.",
    stage: "idea",
    score: 7.3, tier: "A",
    market: 8, pain: 8, mono: 9, speed: 6, competition: 5,
    audience: "B2B SaaS компании $1-10M ARR",
    price: "$199-399/мес",
    tags: ["AI Agent", "SaaS", "Onboarding", "Retention"],
    competitors: ["Intercom (триггерный, не agentic)", "Appcues (триггерный)", "Userflow (триггерный)"],
    createdAt: "2026-03-11",
    whyNow: "B2B SaaS теряет 20-40% клиентов в первые 90 дней. Customer Success менеджеры не успевают. Существующие инструменты if/then — не AI. Нет агента который сам анализирует поведение и решает что делать.",
    risks: ["Интеграция с разными продуктами (нужен product analytics)", "Нужен доступ к usage data клиента", "Долгий sales cycle в B2B SaaS"],
    nextSteps: ["Interview 15 Customer Success менеджеров", "MVP: интеграция с Segment/Mixpanel → персонализированные emails", "Тест с 3 SaaS компаниями (бесплатно)", "Показать снижение churn на 5%+ = продажа"],
  },
  {
    id: "020-churn-predict-agent",
    title: "ChurnPredictAgent",
    description: "AI агент предсказывает какие клиенты уйдут в следующие 30 дней → сам проводит персонализированную re-engagement кампанию.",
    stage: "idea",
    score: 7.3, tier: "A",
    market: 8, pain: 9, mono: 9, speed: 5, competition: 5,
    audience: "B2B SaaS $1-10M ARR без CS команды",
    price: "$299-499/мес",
    tags: ["AI Agent", "SaaS", "Churn", "Retention"],
    competitors: ["ChurnZero ($1000s/мес, enterprise)", "Gainsight ($1000s/мес, enterprise)", "Mixpanel (analytics, не action)"],
    createdAt: "2026-03-11",
    whyNow: "YC RFS 2026: AI agents replacing Customer Success roles. Enterprise платит $1000s/мес. SMB gap огромный. Churn = самая дорогая проблема SaaS.",
    risks: ["Сложный build (10-12 недель)", "Нужен доступ к product analytics данным", "Сложно атрибутировать retention к агенту"],
    nextSteps: ["Targeting: SaaS $1-10M ARR, нет CS менеджера", "Интеграция с Stripe (churn signal) + product analytics", "MVP: churn prediction model → email кампания", "Показать снижение churn = deal"],
  },

  // ─── TIER B ───────────────────────────────────────────────────────────────
  {
    id: "007-seo-agent",
    title: "SEOAgent",
    description: "Агент автономно: находит ключевые слова → пишет статьи → публикует → мониторит позиции → итерирует на основе данных.",
    stage: "idea",
    score: 6.2, tier: "B",
    market: 8, pain: 7, mono: 7, speed: 4, competition: 5,
    audience: "SaaS компании, content маркетологи",
    price: "$500/мес или % от органического трафика",
    tags: ["AI Agent", "SEO", "Content", "Marketing"],
    competitors: ["Surfer SEO", "Jasper", "Clearscope", "MarketMuse", "Frase"],
    createdAt: "2026-03-11",
    whyNow: "SEO остаётся главным каналом для B2B SaaS. AI сделал контент-генерацию доступной. Но full autonomous pipeline (от research до публикации и итерации) никто не делает.",
    risks: ["Высокая конкуренция (десятки AI SEO tools)", "Google может изменить отношение к AI контенту", "Сложный build (4-6 мес до результата виден)"],
    nextSteps: ["Исследовать глубже, не строить сейчас", "Следить за конкурентами", "Revisit если найдёшь незанятую нишу"],
  },
  {
    id: "008-recruitment-agent",
    title: "RecruitmentAgent",
    description: "Ищет кандидатов → проводит технический скрининг → организует интервью → суммаризирует результаты для HR.",
    stage: "idea",
    score: 6.6, tier: "B",
    market: 8, pain: 8, mono: 8, speed: 4, competition: 5,
    audience: "HR менеджеры, стартапы, рекрутинговые агентства",
    price: "$500 за кандидата прошедшего screening",
    tags: ["AI Agent", "HR", "Recruitment", "Automation"],
    competitors: ["Greenhouse", "Lever", "LinkedIn Recruiter", "Ashby"],
    createdAt: "2026-03-11",
    whyNow: "Рекрутмент — болезненный и дорогой процесс. AI может автоматизировать screening. Outcome-based pricing ($500/кандидат) — компании легко видят ROI.",
    risks: ["LinkedIn строго ограничивает scraping", "Сложный build (интеграция с ATS системами)", "Юридические вопросы bias в AI скрининге"],
    nextSteps: ["Не строить сейчас из-за LinkedIn ограничений", "Исследовать alternative data sources", "Revisit в 2027"],
  },
  {
    id: "009-amazon-margin",
    title: "Amazon Margin Guardian",
    description: "Единственный инструмент который мониторит маржу по каждому ASIN в реальном времени с алертами при изменении себестоимости или комиссий Amazon.",
    stage: "idea",
    score: 6.8, tier: "B",
    market: 8, pain: 8, mono: 7, speed: 7, competition: 4,
    audience: "Amazon FBA sellers с 10+ SKU",
    price: "$29-49/мес",
    tags: ["SaaS", "Amazon", "Finance", "Monitor"],
    competitors: ["Helium10 (может добавить фичу)", "JungleScout (может добавить)", "SellerApp"],
    createdAt: "2026-03-11",
    whyNow: "Amazon часто меняет FBA fees. Sellers теряют маржу не замечая. Нет специализированного real-time margin tracker.",
    risks: ["Helium10/JungleScout могут добавить эту фичу за 2 мес", "Зависимость от Amazon Seller API", "Строить только после ListingAgent"],
    nextSteps: ["Строить после ListingAgent достигает $5k MRR", "Может быть feature в ListingAgent, не отдельный продукт"],
  },
  {
    id: "010-sales-brief",
    title: "AI Pre-Call Sales Brief",
    description: "AI автоматически готовит «battle card» перед каждым sales звонком за 2 минуты вместо 30-60 минут ручного research.",
    stage: "idea",
    score: 6.4, tier: "B",
    market: 7, pain: 7, mono: 7, speed: 6, competition: 5,
    audience: "SDR, Account Executive, B2B sales teams",
    price: "$49-99/мес",
    tags: ["AI", "Sales", "B2B", "Productivity"],
    competitors: ["LinkedIn Sales Navigator (данные)", "Clari", "Gong", "Momentum"],
    createdAt: "2026-03-11",
    whyNow: "SDR тратят 30-60 мин на research перед каждым звонком. AI может делать это за 2 мин. Outcome измерим: больше звонков в день.",
    risks: ["LinkedIn Sales Navigator имеет преимущество по данным", "Точность research данных из открытых источников", "Сложно дифференцироваться"],
    nextSteps: ["Исследовать как потенциальный feature в OutreachAgent", "Не строить как отдельный продукт сейчас"],
  },
  {
    id: "018-accountant-inbox",
    title: "AccountantInboxAgent",
    description: "AI агент для бухгалтеров: объединяет переписку из email, QuickBooks, WhatsApp в один inbox + автоматически категоризирует задачи клиентов.",
    stage: "idea",
    score: 6.7, tier: "B",
    market: 7, pain: 7, mono: 7, speed: 6, competition: 6,
    audience: "Solo бухгалтеры и small bookkeeping firms",
    price: "$49-99/мес",
    tags: ["AI Agent", "Finance", "Accounting", "Productivity"],
    competitors: ["Karbon ($59+/user/мес, дорогой)", "Financial Cents ($39+/мес)", "TaxDome"],
    createdAt: "2026-03-11",
    whyNow: "Налоговый сезон = хаос из-за разрозненной переписки. Reddit r/accounting: «client communication scattered across email, QuickBooks, and text». AI может объединить всё.",
    risks: ["Интеграция с QuickBooks Messages сложная", "WhatsApp Business API ограничения", "Сложно убедить бухгалтеров менять workflow"],
    nextSteps: ["Исследовать глубже перед build", "Interview 10 solo бухгалтеров", "Проверить QuickBooks API возможности"],
  },

  // ─── LEGACY IDEAS (уникальные, не в банке) ─────────────────────────────
  {
    id: "shopify-abandoned-cart",
    title: "Shopify Abandoned Cart AI",
    description: "AI пишет персонализированные email/SMS follow-up для брошенных корзин, анализируя историю покупок и продукт.",
    stage: "idea",
    score: 8.0, tier: "S",
    market: 9, pain: 8, mono: 9, speed: 7, competition: 7,
    audience: "Shopify merchants (4.6M магазинов)",
    price: "$49/мес + % от recovered revenue",
    tags: ["AI", "E-commerce", "Email", "Shopify"],
    competitors: ["Klaviyo", "Omnisend", "Drip", "Postscript"],
    createdAt: "2026-03-03",
    whyNow: "70% корзин брошены. Recovery = прямые деньги. Нет AI-native решения специально для этого.",
    risks: ["Klaviyo может добавить AI", "Shopify может встроить это в платформу", "Высокая конкуренция в email маркетинге"],
    nextSteps: ["Анализ отзывов на Klaviyo в App Store", "Создать Shopify app account", "Прототип email генератора", "Запустить на Shopify App Store"],
  },
  {
    id: "grant-tracker",
    title: "Grant Tracker for Nonprofits",
    description: "Отслеживает доступные гранты, дедлайны, статус заявок для некоммерческих организаций.",
    stage: "idea",
    score: 7.8, tier: "S",
    market: 7, pain: 9, mono: 7, speed: 8, competition: 8,
    audience: "Small nonprofits (1.5M в США)",
    price: "$49/мес",
    tags: ["SaaS", "Nonprofit"],
    competitors: ["GrantStation", "Instrumentl", "Submittable"],
    createdAt: "2026-03-04",
    whyNow: "Почти нет специализированных доступных инструментов. Nonprofits теряют гранты из-за пропущенных дедлайнов.",
    risks: ["Низкая платёжеспособность НКО", "Длинный цикл продаж", "Нужны данные о грантах"],
    nextSteps: ["Найти 5 nonprofit директоров для интервью", "Проверить API источников грантов", "MVP с email алертами"],
  },
  {
    id: "competitor-monitor",
    title: "Competitor Price Monitor",
    description: "Мониторит цены конкурентов на конкретной нише и присылает алерты когда они меняются.",
    stage: "idea",
    score: 7.4, tier: "A",
    market: 7, pain: 8, mono: 8, speed: 8, competition: 6,
    audience: "E-commerce sellers, SaaS founders",
    price: "$29-49/мес",
    tags: ["SaaS", "Pricing", "Monitor"],
    competitors: ["Price2Spy", "Prisync", "Wiser", "Kompyte"],
    createdAt: "2026-03-08",
    whyNow: "E-commerce конкуренция растёт. Цена — главный фактор. Нет нишевых решений для малого бизнеса.",
    risks: ["Блокировка scrapers", "Юридические вопросы", "Точность данных"],
    nextSteps: ["Выбрать нишу — Etsy или Shopify", "Создать простой scraper", "Тест с 5 beta пользователями"],
  },
  {
    id: "linkedin-scheduler",
    title: "LinkedIn Post AI Scheduler",
    description: "AI пишет LinkedIn посты в твоём стиле на неделю вперёд, ты апрувишь, они публикуются автоматически.",
    stage: "idea",
    score: 7.4, tier: "A",
    market: 8, pain: 7, mono: 8, speed: 8, competition: 6,
    audience: "B2B founders, консультанты, продавцы",
    price: "$29-49/мес",
    tags: ["AI", "LinkedIn", "Content"],
    competitors: ["Buffer", "Taplio", "Shield", "Hootsuite"],
    createdAt: "2026-03-09",
    whyNow: "LinkedIn алгоритм вознаграждает частоту. Founders знают что надо постить, но нет времени.",
    risks: ["LinkedIn API ограничения", "Конкуренция с Taplio", "Сложно обучить AI на стиль пользователя"],
    nextSteps: ["Исследовать LinkedIn API", "Survey 20 B2B founders", "MVP: генерация + ручное копирование"],
  },
  {
    id: "airbnb-toolkit",
    title: "Airbnb Host Toolkit",
    description: "Пакет инструментов для Airbnb хостов: AI для ответов гостям, автоматизация отзывов, динамическое ценообразование.",
    stage: "idea",
    score: 7.4, tier: "A",
    market: 8, pain: 7, mono: 8, speed: 7, competition: 7,
    audience: "Airbnb hosts (8M+ активных)",
    price: "$39/мес",
    tags: ["AI", "Airbnb", "Hosting"],
    competitors: ["Guesty", "Hospitable", "Lodgify", "Hostaway"],
    createdAt: "2026-03-10",
    whyNow: "Количество Airbnb хостов растёт. Управление сложное. Нет доступного AI инструмента.",
    risks: ["Зависимость от Airbnb API", "Airbnb может ограничить интеграции", "Конкуренция с PMS системами"],
    nextSteps: ["Опросить 10 хостов на Reddit r/airbnb", "Определить главную боль", "MVP только для одной функции"],
  },
  {
    id: "social-proof",
    title: "Social Proof Aggregator",
    description: "Собирает отзывы с Google, Trustpilot, G2, Twitter в одно место и создаёт виджеты для сайта.",
    stage: "idea",
    score: 7.2, tier: "A",
    market: 8, pain: 7, mono: 8, speed: 8, competition: 5,
    audience: "SaaS компании, агентства, e-commerce",
    price: "$29-79/мес",
    tags: ["SaaS", "Marketing", "Reviews"],
    competitors: ["Testimonial.to", "Senja", "Trustmary", "Proof"],
    createdAt: "2026-03-10",
    whyNow: "Социальное доказательство критично для конверсии. Отзывы разбросаны по десяткам платформ.",
    risks: ["API ограничения платформ", "Конкуренция с Testimonial.to", "Модерация контента"],
    nextSteps: ["Исследовать API Google Reviews, G2", "Определить дифференциацию", "Waitlist лендинг"],
  },
]
